import AppKit
import Foundation
import Carbon

/// Clipboard history adapted from Maccy (MIT): poll NSPasteboard.changeCount.
struct ClipboardItem: Identifiable, Equatable {
    enum Kind: String, Codable, CaseIterable {
        case text
        case image
        case file

        var title: String {
            switch self {
            case .text: return "文本"
            case .image: return "图片"
            case .file: return "文件"
            }
        }
    }

    var id: UUID
    var kind: Kind
    var createdAt: Date
    var preview: String
    var text: String?
    var imagePath: String?
    var filePaths: [String]
    var byteCount: Int64
    var isFavorite: Bool
    var thumbPath: String?

    var previewSourcePath: String? {
        if let thumbPath, FileManager.default.fileExists(atPath: thumbPath) { return thumbPath }
        if kind == .image { return imagePath }
        if kind == .file, let path = filePaths.first, ClipboardItem.isImageFile(path) {
            return path
        }
        return nil
    }

    var sizeLabel: String {
        switch kind {
        case .text:
            let n = text?.count ?? preview.count
            return "\(n) 个字符"
        case .image, .file:
            return ByteCountFormatter.string(fromByteCount: byteCount, countStyle: .file)
        }
    }

    var timeLabel: String {
        let minutes = Int(Date().timeIntervalSince(createdAt) / 60)
        if minutes < 1 { return "刚刚" }
        if minutes < 60 { return "\(minutes) 分钟前" }
        let hours = minutes / 60
        if hours < 24 { return "\(hours) 小时前" }
        let formatter = DateFormatter()
        formatter.dateFormat = "MM月dd日"
        return formatter.string(from: createdAt)
    }

    static func isImageFile(_ path: String) -> Bool {
        let ext = (path as NSString).pathExtension.lowercased()
        return ["png", "jpg", "jpeg", "gif", "webp", "tif", "tiff", "heic", "bmp"].contains(ext)
    }
}

@MainActor
final class ClipboardStore: ObservableObject {
    @Published var items: [ClipboardItem] = []
    @Published var hotKey: HotKeySpec
    @Published var recordingHotKey = false

    private let pasteboard = NSPasteboard.general
    private var changeCount: Int
    private var ignoreUntilCount: Int?
    private var timer: Timer?
    private var keyMonitor: Any?
    private let limit = 80
    private let root: URL
    private let imagesDir: URL
    private let indexURL: URL

    private let ignoredTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType"
    ]

    init() {
        changeCount = pasteboard.changeCount
        let support = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
            .appendingPathComponent("OneBar", isDirectory: true)
        root = support.appendingPathComponent("clipboard", isDirectory: true)
        imagesDir = root.appendingPathComponent("images", isDirectory: true)
        indexURL = root.appendingPathComponent("index.json")
        try? FileManager.default.createDirectory(at: imagesDir, withIntermediateDirectories: true)
        try? FileManager.default.createDirectory(at: imagesDir.appendingPathComponent("thumbs", isDirectory: true), withIntermediateDirectories: true)

        let storedCode = UserDefaults.standard.object(forKey: "onebar.clip.keyCode") as? Int
        let storedMods = UserDefaults.standard.object(forKey: "onebar.clip.modifiers") as? Int
        if let storedCode, let storedMods {
            hotKey = HotKeySpec(keyCode: UInt32(storedCode), modifiers: UInt32(storedMods))
        } else {
            hotKey = .defaultClip
        }

        load()
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in self?.poll() }
        }
    }

    func persistHotKey() {
        UserDefaults.standard.set(Int(hotKey.keyCode), forKey: "onebar.clip.keyCode")
        UserDefaults.standard.set(Int(hotKey.modifiers), forKey: "onebar.clip.modifiers")
        HotKeyCenter.shared.register(hotKey)
    }

    func beginRecordHotKey() {
        recordingHotKey = true
        if keyMonitor == nil {
            keyMonitor = NSEvent.addLocalMonitorForEvents(matching: .keyDown) { [weak self] event in
                guard let self, self.recordingHotKey else { return event }
                if event.keyCode == UInt16(kVK_Escape) {
                    self.recordingHotKey = false
                    return nil
                }
                if let spec = HotKeySpec.from(event: event) {
                    self.hotKey = spec
                    self.persistHotKey()
                    self.recordingHotKey = false
                    return nil
                }
                return event
            }
        }
    }

    func restore(_ item: ClipboardItem) {
        pasteboard.clearContents()
        switch item.kind {
        case .text:
            pasteboard.setString(item.text ?? item.preview, forType: .string)
        case .image:
            if let path = item.imagePath,
               let data = try? Data(contentsOf: URL(fileURLWithPath: path)) {
                pasteboard.setData(data, forType: .png)
            }
        case .file:
            let urls = item.filePaths.map { URL(fileURLWithPath: $0) as NSURL }
            pasteboard.writeObjects(urls)
        }
        ignoreUntilCount = pasteboard.changeCount
    }

    func toggleFavorite(_ item: ClipboardItem) {
        guard let i = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[i].isFavorite.toggle()
        persist()
    }

    func clear() {
        items.removeAll()
        persist()
        if let files = try? FileManager.default.contentsOfDirectory(at: imagesDir, includingPropertiesForKeys: nil) {
            for file in files { try? FileManager.default.removeItem(at: file) }
        }
    }

    func remove(_ item: ClipboardItem) {
        items.removeAll { $0.id == item.id }
        if let path = item.imagePath {
            try? FileManager.default.removeItem(at: URL(fileURLWithPath: path))
        }
        persist()
    }

    private func poll() {
        let current = pasteboard.changeCount
        guard current != changeCount else { return }
        changeCount = current
        if let skip = ignoreUntilCount, current <= skip {
            return
        }
        ignoreUntilCount = nil
        capture()
    }

    private func capture() {
        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        if !ignoredTypes.isDisjoint(with: types) { return }

        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty, urls.allSatisfy(\.isFileURL) {
            let paths = urls.map(\.path)
            if items.first?.filePaths == paths { return }
            let bytes = paths.reduce(Int64(0)) { sum, path in
                let n = (try? FileManager.default.attributesOfItem(atPath: path)[.size] as? NSNumber)?.int64Value ?? 0
                return sum + n
            }
            prepend(ClipboardItem(
                id: UUID(),
                kind: .file,
                createdAt: Date(),
                preview: urls.map(\.lastPathComponent).joined(separator: ", "),
                text: nil,
                imagePath: nil,
                filePaths: paths,
                byteCount: bytes,
                isFavorite: false,
                thumbPath: Self.makeThumb(from: paths.first)
            ))
            return
        }

        if let data = pasteboard.data(forType: .png) ?? tiffAsPNG() {
            if data.count > 20 * 1024 * 1024 { return }
            let id = UUID()
            let file = imagesDir.appendingPathComponent("\(id.uuidString).png")
            do { try data.write(to: file, options: .atomic) } catch { return }
            prepend(ClipboardItem(
                id: id,
                kind: .image,
                createdAt: Date(),
                preview: "图片",
                text: nil,
                imagePath: file.path,
                filePaths: [],
                byteCount: Int64(data.count),
                isFavorite: false,
                thumbPath: Self.makeThumb(from: file.path)
            ))
            return
        }

        if let text = pasteboard.string(forType: .string)?.trimmingCharacters(in: .whitespacesAndNewlines),
           !text.isEmpty {
            if items.first?.text == text { return }
            let preview = text.count > 80 ? String(text.prefix(80)) + "…" : text
            prepend(ClipboardItem(
                id: UUID(),
                kind: .text,
                createdAt: Date(),
                preview: preview.replacingOccurrences(of: "\n", with: " "),
                text: text,
                imagePath: nil,
                filePaths: [],
                byteCount: Int64(text.utf8.count),
                isFavorite: false,
                thumbPath: nil
            ))
        }
    }

    private func tiffAsPNG() -> Data? {
        guard let tiff = pasteboard.data(forType: .tiff),
              let image = NSImage(data: tiff),
              let tiffRep = image.tiffRepresentation,
              let rep = NSBitmapImageRep(data: tiffRep) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }

    private func prepend(_ item: ClipboardItem) {
        items.insert(item, at: 0)
        while items.count > limit {
            let removed = items.removeLast()
            if let path = removed.imagePath {
                try? FileManager.default.removeItem(at: URL(fileURLWithPath: path))
            }
            if let path = removed.thumbPath {
                try? FileManager.default.removeItem(at: URL(fileURLWithPath: path))
            }
        }
        persist()
    }

    private static func makeThumb(from source: String?) -> String? {
        guard let source, FileManager.default.fileExists(atPath: source) else { return nil }
        if !ClipboardItem.isImageFile(source), (source as NSString).pathExtension.lowercased() != "png" {
            return nil
        }
        let support = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
            .appendingPathComponent("OneBar/clipboard/images/thumbs", isDirectory: true)
        let dest = support.appendingPathComponent("\(UUID().uuidString).jpg")
        return ThumbnailMaker.write(from: source, to: dest) ? dest.path : nil
    }

    private struct DiskItem: Codable {
        var id: UUID
        var kind: ClipboardItem.Kind
        var createdAt: Date
        var preview: String
        var text: String?
        var imagePath: String?
        var filePaths: [String]
        var byteCount: Int64?
        var isFavorite: Bool?
        var thumbPath: String?
    }

    private func persist() {
        let payload = items.map {
            DiskItem(id: $0.id, kind: $0.kind, createdAt: $0.createdAt, preview: $0.preview,
                     text: $0.text, imagePath: $0.imagePath, filePaths: $0.filePaths,
                     byteCount: $0.byteCount, isFavorite: $0.isFavorite, thumbPath: $0.thumbPath)
        }
        guard let data = try? JSONEncoder().encode(payload) else { return }
        try? data.write(to: indexURL, options: .atomic)
    }

    private func load() {
        guard let data = try? Data(contentsOf: indexURL),
              let payload = try? JSONDecoder().decode([DiskItem].self, from: data) else { return }
        items = payload.map {
            var bytes = $0.byteCount ?? 0
            if bytes == 0 {
                if let path = $0.imagePath {
                    bytes = (try? FileManager.default.attributesOfItem(atPath: path)[.size] as? NSNumber)?.int64Value ?? 0
                } else {
                    bytes = $0.filePaths.reduce(Int64(0)) { sum, path in
                        sum + ((try? FileManager.default.attributesOfItem(atPath: path)[.size] as? NSNumber)?.int64Value ?? 0)
                    }
                }
            }
            return ClipboardItem(id: $0.id, kind: $0.kind, createdAt: $0.createdAt, preview: $0.preview,
                          text: $0.text, imagePath: $0.imagePath, filePaths: $0.filePaths,
                          byteCount: bytes, isFavorite: $0.isFavorite ?? false, thumbPath: $0.thumbPath)
        }
    }
}
